import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/navigation/sidebar";
import { ThemeProvider } from "@/components/theme-provider";


const dosis = Dosis({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-dosis",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dosis.variable} font-sans antialiased p-10`} // Apply Nunito
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <div className="flex relative max-w-screen-xl min-h-screen m-auto bg-[#F6F4FA] rounded-3xl">
            {/* Sidebar */}
            <aside className="relative">
              <Sidebar />
            </aside>

            {/* Main Content */}
            <main className="flex-1 p-6 ms-28">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
