import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/navigation/sidebar";

import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen p-10`}
    >
      <ThemeProvider attribute="class" defaultTheme="system">
      <div className="flex relative max-w-screen-xl m-auto
                  bg-[#F6F4FA]
                  rounded-3xl">
            {/* Sidebar */}
            <aside className="relative">
              <Sidebar />
            </aside>

            {/* Contenido principal */}
            <main className="flex-1 p-6 ms-28">
              {children}
            </main>
          </div>
      </ThemeProvider>
    </body>
  </html>
  );
}
